package com.wunderfleet.feat_feature_repo_list.model

import android.os.Parcelable
import com.wunderfleet.feat_domain_repo_list.model.GithubRepoModel
import kotlinx.android.parcel.Parcelize

@Parcelize
class RepoModel(
    var id: Int? = null,
    var owner: OwnerModelView? = null,
    var node_id: String? = null,
    var name: String? = null,
    var full_name: String? = null,
    var private: Boolean? = null,
    var html_url: String? = null,
    var description: String? = null,
    var fork: Boolean? = null,
    var url: String? = null,
    var forks_url: String? = null,
    var keys_urls_url: String? = null,
    var collaborators_url: String? = null,
    var teams_url: String? = null,
    var hooks_url: String? = null,
    var issue_events_url: String? = null,
    var events_url: String? = null,
    var assignees_url: String? = null,
    var branches_url: String? = null,
    var tags_url: String? = null,
    var blobs_url: String? = null,
    var git_tags_url: String? = null,
    var git_refs_url: String? = null,
    var trees_url: String? = null,
    var statuses_url: String? = null,
    var languages_url: String? = null,
    var stargazers_url: String? = null,
    var contributors_url: String? = null,
    var subscribers_url: String? = null,
    var subscription_url: String? = null,
    var commits_url: String? = null,
    var git_commits_url: String? = null,
    var comments_url: String? = null,
    var issue_comment_url: String? = null,
    var contents_url: String? = null,
    var compare_url: String? = null,
    var merges_url: String? = null,
    var archive_url: String? = null,
    var downloads_url: String? = null,
    var issues_url: String? = null,
    var pulls_url: String? = null,
    var milestones_url: String? = null,
    var notifications_url: String? = null,
    var labels_url: String? = null,
    var releases_url: String? = null,
    var deployments_url: String? = null,
    var created_at: String? = null,
    var updated_at: String? = null,
    var pushed_at: String? = null,
    var git_url: String? = null,
    var ssh_url: String? = null,
    var clone_url: String? = null,
    var svn_url: String? = null,
    var homepage: String? = null,
    var size: Int? = null,
    var stargazers_count: Int? = null,
    var watchers_count: Int? = null,
    var language: String? = null,
    var has_issues: Boolean? = null,
    var has_projects: Boolean? = null,
    var has_downloads: Boolean? = null,
    var has_wiki: Boolean? = null,
    var has_pages: Boolean? = null,
    var forks_count: Int? = null,
    var mirror_url: String? = null,
    var archived: Boolean? = null,
    var disabled: Boolean? = null,
    var open_issues_count: Int? = null,
    var license: String? = null,
    var forks: Int? = null,
    var open_issues: Int? = null,
    var watchers: Int? = null,
    var default_branch: String? = null
) : Parcelable

fun GithubRepoModel.mapToView(): RepoModel = RepoModel(
    this.id,
    this.owner?.mapToView(),
    this.node_id,
    this.name,
    this.full_name,
    this.private,
    this.html_url,
    this.description,
    this.fork,
    this.url,
    this.forks_url,
    this.keys_urls_url,
    this.collaborators_url,
    this.teams_url,
    this.hooks_url,
    this.issue_events_url,
    this.events_url,
    this.assignees_url,
    this.branches_url,
    this.tags_url,
    this.blobs_url,
    this.git_tags_url,
    this.git_refs_url,
    this.trees_url,
    this.statuses_url,
    this.languages_url,
    this.stargazers_url,
    this.contributors_url,
    this.subscribers_url,
    this.subscription_url,
    this.commits_url,
    this.git_commits_url,
    this.comments_url,
    this.issue_comment_url,
    this.contents_url,
    this.compare_url,
    this.merges_url,
    this.archive_url,
    this.downloads_url,
    this.issues_url,
    this.pulls_url,
    this.milestones_url,
    this.notifications_url,
    this.labels_url,
    this.releases_url,
    this.deployments_url,
    this.created_at,
    this.updated_at,
    this.pushed_at,
    this.git_url,
    this.ssh_url,
    this.clone_url,
    this.svn_url,
    this.homepage,
    this.size,
    this.stargazers_count,
    this.watchers_count,
    this.language,
    this.has_issues,
    this.has_projects,
    this.has_downloads,
    this.has_wiki,
    this.has_pages,
    this.forks_count,
    this.mirror_url,
    this.archived,
    this.disabled,
    this.open_issues_count,
    this.license,
    this.forks,
    this.open_issues,
    this.watchers,
    this.default_branch
)